### ISSUE TITLE
Have a mistake?

### ISSUE THREAD

**Issue by ucasiggcas** [smousavi05/Denoising-BTwavelet#1]
In the demo.m file,   case 'synth'  
you set data.t=linspace(0,(100),length(data.x))    and  data.dt = 0.01
but after processing, I find the length(data.x)) = 1001, so its sample time interval data.dt should be about 0.1 ,but your data.dt is 0.01 ,is this right ?

**Comment by smousavi05** [comment]
No, the sampling (data.dt) is the inherent sampling of the synthetic data (data.x). Although you can make data.t to be the same size as the data.x, but for the sake of a short example and demonstration it doesn't make any difference to ignore one sample from the data (data.x) and make the associated time vector (data.t) one sample shorter. None of these would make any problem for the implementation of the denoising as long as both data and time vectors have the same length.

**Comment by ucasiggcas** [comment]
Thank you for your reply.
But I still a little confused. I mean not just ONE sample !
You said, you have downsampling about the data.x or something else ?
According to your data.dt, the number (100) in data.t should be 10, and if I set as this, the result is very bad, but when I set the number be 200, the result is better than yours, so what' s the rule to choose the number ? Is the number has relationship of time ?

**Comment by smousavi05** [comment]
I just got your point sorry for the confusions. The sampling interval should be 0.1. I will correct and update it. Thanks for the comment btw.

**Comment by ucasiggcas** [comment]
Thanks a lot, 
I will think over the number' chioce for different results .
I also have a question about SNR in real data, how to calculate the SNR when you don't know the REAL signal ?

**Comment by smousavi05** [comment]
The way seismologists calculate the SNR of real data is to select one window after and one window before the onset time (arrival of seismic energy-usually P) and then calculate and divide the RMS amplitude of these two. 
 I also recommend you to check out our CGV algorithm. It is our latest and fastest denoising algorithm.

**Comment by ucasiggcas** [comment]
CGV ？ Not GCV ？
Have read the latter, also have the same mistake, should be 0.1, not 0.01 !

**Comment by smousavi05** [comment]
Yeah GCV. That is correct the transform part is similar. For the synthetic example need to be changed to 0.1 but for the real one 0.01 is correct.
